<?php
    require 'connection.php';
    $Extension_activities=$_POST['extension'];
    $Extension_activities= mysqli_real_escape_string($conn,$Extension_activities);
    $link=$_POST['link'];
    $link= mysqli_real_escape_string($conn,$link);
    $Number_awards=$_POST['numberofawards'];
    $Number_awards= mysqli_real_escape_string($conn,$Number_awards);
    $Number_awards_2019=$_POST['num_1'];
    $Number_awards_2019= mysqli_real_escape_string($conn,$Number_awards_2019);
    $Number_awards_2018=$_POST['num_2'];
    $Number_awards_2018= mysqli_real_escape_string($conn,$Number_awards_2018);
    $Number_awards_2017=$_POST['num_3'];
    $Number_awards_2017= mysqli_real_escape_string($conn,$Number_awards_2017);
    $Number_awards_2016=$_POST['num_4'];
    $Number_awards_2016= mysqli_real_escape_string($conn,$Number_awards_2016);
    $Number_awards_2015=$_POST['num_5'];
    $Number_awards_2015= mysqli_real_escape_string($conn,$Number_awards_2015);
    $Extension_programs=$_POST['numberofextension'];
    $Extension_programs= mysqli_real_escape_string($conn,$Extension_programs);
    $Extension_programs_2019=$_POST['num_6'];
    $Extension_programs_2019= mysqli_real_escape_string($conn,$Extension_programs_2019);
    $Extension_programs_2018=$_POST['num_7'];
    $Extension_programs_2018= mysqli_real_escape_string($conn,$Extension_programs_2018);
    $Extension_programs_2017=$_POST['num_8'];
    $Extension_programs_2017= mysqli_real_escape_string($conn,$Extension_programs_2017);
    $Extension_programs_2016=$_POST['num_9'];
    $Extension_programs_2016= mysqli_real_escape_string($conn,$Extension_programs_2016);
    $Extension_programs_2015=$_POST['num_10'];
    $Extension_programs_2015= mysqli_real_escape_string($conn,$Extension_programs_2015);
    $Students_participating=$_POST['studentsparticicpating'];
    $Students_participating= mysqli_real_escape_string($conn,$Students_participating);
    $Students_participating_2019=$_POST['num_11'];
    $Students_participating_2019= mysqli_real_escape_string($conn,$Students_participating_2019);
    $Students_participating_2018=$_POST['num_12'];
    $Students_participating_2018= mysqli_real_escape_string($conn,$Students_participating_2018);
    $Students_participating_2017=$_POST['num_13'];
    $Students_participating_2017= mysqli_real_escape_string($conn,$Students_participating_2017);
    $Students_participating_2016=$_POST['num_14'];
    $Students_participating_2016= mysqli_real_escape_string($conn,$Students_participating_2016);
    $Students_participating_2015=$_POST['num_15'];
    $Students_participating_2015= mysqli_real_escape_string($conn,$Students_participating_2015);
    $query="INSERT INTO four(Extension_activities,link,Number_awards,Number_awards_2019,Number_awards_2018,Number_awards_2017,Number_awards_2016,Number_awards_2015,Extension_programs,Extension_programs_2019,Extension_programs_2018,Extension_programs_2017,Extension_programs_2016,Extension_programs_2015,Students_participating,Students_participating_2019,Students_participating_2018,Students_participating_2017,Students_participating_2016,Students_participating_2015)VALUES('$Extension_activities','$link','$Number_awards','$Number_awards_2019','$Number_awards_2018','$Number_awards_2017','$Number_awards_2016','$Number_awards_2015','$Extension_programs','$Extension_programs_2019','$Extension_programs_2018','$Extension_programs_2017','$Extension_programs_2016','$Extension_programs_2015','$Students_participating','$Students_participating_2019','$Students_participating_2018','$Students_participating_2017','$Students_participating_2016','$Students_participating_2015')";
    $result=mysqli_query($conn, $query) or die (mysqli_error($conn));
    header("location: 3.5.php");
?>